export const ActivityCategory = {
  TRANSACTION: 'TRANSACTION',
  TRAFFIC: 'TRAFFIC',
} as const;

export type ActivityCategory = typeof ActivityCategory[keyof typeof ActivityCategory];

export const ActivityType = {
  COLLECTION_CREATED: 'COLLECTION_CREATED',
  COLLECTION_REGISTERED: 'COLLECTION_REGISTERED',
  MINT: 'MINT',
  TRANSFER: 'TRANSFER',
  AUCTION_REGISTERED: 'AUCTION_REGISTERED',
  AUCTION_START: 'AUCTION_START',
  AUCTION_BID: 'AUCTION_BID',
  AUCTION_BID_FIRST: 'AUCTION_BID_FIRST',
  AUCTION_BID_COLLECTION_HIGHEST: 'AUCTION_BID_COLLECTION_HIGHEST',
  AUCTION_BID_NILE_HIGHEST: 'AUCTION_BID_NILE_HIGHEST',
  AUCTION_BID_CANCEL: 'AUCTION_BID_CANCEL',
  AUCTION_BID_CLOSE: 'AUCTION_BID_CLOSE',
  AUCTION_CLAIM: 'AUCTION_CLAIM',
  AUCTION_CANCEL: 'AUCTION_CANCEL',
  AUCTION_END: 'AUCTION_END',
  FIXED_PRICE_REGISTERED: 'FIXED_PRICE_REGISTERED',
  FIXED_PRICE_OPEN: 'FIXED_PRICE_OPEN',
  FIXED_PRICE_CLOSE: 'FIXED_PRICE_CLOSE',
  FIXED_PRICE_COMPLETE: 'FIXED_PRICE_COMPLETE',
  FIXED_PRICE_CANCEL: 'FIXED_PRICE_CANCEL',
  OPEN_PRICE_OPEN: 'OPEN_PRICE_OPEN',
  OPEN_PRICE_OPEN_FIRST: 'OPEN_PRICE_OPEN_FIRST',
  OPEN_PRICE_CANCEL: 'OPEN_PRICE_CANCEL',
  OPEN_PRICE_EXPIRED: 'OPEN_PRICE_EXPIRED',
  OPEN_PRICE_CLOSE: 'OPEN_PRICE_CLOSE',
  OPEN_PRICE_COMPLETE: 'OPEN_PRICE_COMPLETE',
  OFFER_MAKE: 'OFFER_MAKE',
  OFFER_CANCEL: 'OFFER_CANCEL',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  OFFER_COMPLETE: 'OFFER_COMPLETE',

  // traffic
  COLLECTION_SHARE: 'COLLECTION_SHARE',
  COLLECTION_LIKE: 'COLLECTION_LIKE',
  TOKEN_VIEW: 'TOKEN_VIEW',
  TOKEN_SHARE: 'TOKEN_SHARE',
  TOKEN_LIKE: 'TOKEN_LIKE',
  CONNECT_WALLET: 'CONNECT_WALLET',
  COLLECTION_HIGH_BID: 'COLLECTION_HIGH_BID',
  NILE_HIGH_BID: 'NILE_HIGH_BID',
  COLLECTION_HIGH_PURCHASE: 'COLLECTION_HIGH_PURCHASE',
  NILE_HIGH_PURCHASE: 'NILE_HIGH_PURCHASE',
} as const;

export type ActivityType = typeof ActivityType[keyof typeof ActivityType];

export type Activity = {
  id: string,
  category: ActivityCategory,
  type: ActivityType,
  timestamp: string,
  tx?: string,
  collection?: string,
  tokenId?: number,
  from?: string,
  fromName?: string,
  fromImage?: string,
  fromTheme?: number,
  to?: string,
  toName?: string,
  toImage?: string,
  toTheme?: number,
  guest?: string,
  price?: string,
  payment?: string,
}